# Generated by Django 4.0.1 on 2022-01-11 06:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category safe URL')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='property.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('description', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='description')),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 a and 99999999.99'}}, help_text='Maximum 99999999.99', max_digits=12, verbose_name='Property Price')),
                ('is_active', models.BooleanField(default=True, help_text='Change property visibility', verbose_name='Property for sale')),
                ('property_location', models.CharField(max_length=255)),
                ('location_link', models.URLField()),
                ('document_file', models.FileField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agent.agent')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='property.category')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Property',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Feature Group Title')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Property Features',
                'verbose_name_plural': 'Property Features',
            },
        ),
        migrations.CreateModel(
            name='PropertySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Name')),
                ('property_features', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='property.propertyfeature')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Property specification value (maximum of 255 words)', max_length=255, verbose_name='value')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='property.propertyspecification')),
            ],
            options={
                'verbose_name': 'Property specification Value',
                'verbose_name_plural': 'Property Specification Value',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload a property image', upload_to='images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text')),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
            },
        ),
    ]
