# Generated by Django 4.0.1 on 2022-01-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='specification',
            field=models.ManyToManyField(to='property.PropertySpecification'),
        ),
    ]
