# Generated by Django 4.0.1 on 2022-01-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='specification',
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(to='property.PropertyFeature'),
        ),
    ]
