# Generated by Django 4.0.1 on 2022-01-13 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_specification_property_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyspecification',
            name='property_features',
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='property_features',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyspecification',
            name='specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.propertyfeature'),
            preserve_default=False,
        ),
    ]
