# Generated by Django 4.0.1 on 2022-01-13 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_propertyfeature_property_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyspecification',
            old_name='specification',
            new_name='feature',
        ),
        migrations.AlterField(
            model_name='propertyspecificationvalue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_specification_value', to='property.property'),
        ),
    ]
